
name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

# 👇 IMPORTANT: allow the job to push to the repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: anushkalowanshi
          outputs: dist/github-contribution-grid-snake.svg

      - name: push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
